# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node Github CI

on:
  repository_dispatch:
    types: [dockerhub_push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout docker compose prod
        uses: actions/checkout@v2
      - name: copy via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./docker-compose-prod.yml"
          target: ~/backend
      - name: checkout docker compose prod
        uses: actions/checkout@v2
      - name: copy via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./docker/*"
          target: ~/backend
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/backend
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
            docker compose -f docker-compose-prod.yml down
            docker rmi -f hikaruyuzu/bingleshop-backend-api:latest
            docker compose -f docker-compose-prod.yml pull
            docker compose -f docker-compose-prod.yml up -d

          
         
            




